export enum MOVIE {
  SET_ALL_MOVIES = 'SET_ALL_MOVIES',
  SET_GENRE_MOVIE = 'SET_GENRE',
  SET_ALL_MOVIES_POPULAR = 'SET_ALL_MOVIES_POPULAR',
  SET_DETAILS_MOVIE = 'SET_DETAILS_MOVIE',
  SET_CLEAR_DETAILS_MOVIE = 'SET_CLEAR_DETAILS_MOVIE',
  SET_LIKE_MOVIE = 'SET_LIKE_MOVIE',
}
